export const Krs = [
    // {
    //     'sno'   : 1,
    //     'Title' : 'Full Stack Web Development',
    //     // 'watchT': ''
    //     'isPaid'  :  false,
    //     'platform': 'Youtube',
    //     'Link' : '',
    //     'context' : 'about my course Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae odit recusandae ipsa, rem vel, magni illum aut numquam hic maiores asperiores voluptate adipisci officia ad labore necessitatibus reprehenderit in voluptas! Fugiat eum esse quos',
    //     // 'imageUrl': require('../assets/cources-tmb/'),
    //     'MainCat': 'Web Development',
    //     'Stack': 'MERN',
    //     'additional': 'Deployment and Interview Questions',
    //     'Language' : 'English'
    // },
    {
        'sno'   : 2,
        'Title' : 'TensorFlow 2.0 Crash Course ',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/6g4O5UOH304?si=FPDYO3Xa0VmjH6dL',
        'context' : 'Learn how to use TensorFlow 2.0 in this crash course for beginners. This course will demonstrate how to create neural networks with Python and TensorFlow 2.0.',
        'imageUrl': require('../assets/cources-tmb/tf.jpg'),
        'MainCat': 'Data Science',
        'Stack': 'Python',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 3,
        'Title' : 'Scikit-learn Crash Course - Machine Learning Library for Python',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/6g4O5UOH304?si=FPDYO3Xa0VmjH6dL',
        'context' : 'Scikit-learn is a free software machine learning library for the Python programming language. Learn how to use it in this crash course.',
        'imageUrl': require('../assets/cources-tmb/skl.jpg'),
        'MainCat': 'Data Science',
        'Stack': 'Python',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 4,
        'Title' : 'Pandas & Python for Data Analysis by Example – Full Course for Beginners',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/gtjxAH8uaP0?si=hmaA3I93N1HAQNy2',
        'context' : 'Pandas & Python for Data Analysis by Example – Full Course for Beginners. Is one of the best free course avilable on internet where you learn a complete packege of Python data science library.',
        'imageUrl': require('../assets/cources-tmb/pandas.jpg'),
        'MainCat': 'Data Science',
        'Stack': 'Python',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 5,
        'Title' : 'Learn Python Backend Development by Building 3 Projects [Full Course]',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/ftKiHCDVwfA?si=sqO6DpowURoaRPTh',
        'context' : 'This video is a full project-based backend web development course. In this course, you will learn how to build 3 full backend web applications.',
        'imageUrl': require('../assets/cources-tmb/pyBackend.jpg'),
        'MainCat': 'Backend Development',
        'Stack': 'Python',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 6,
        'Title' : 'Numpy Tutorial in Hindi',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/Rbh1rieb3zc?si=k9DlSK3UkbmJ8a-y',
        'context' : 'This Course is a prefet introduction to NumPy, Learn Data science Python Liberary',
        'imageUrl': require('../assets/cources-tmb/harryNumpy.jpg'),
        'MainCat': 'Data Science',
        'Stack': 'Python',
        'additional': '',
        'Language' : 'Hindi'
    },
    {
        'sno'   : 7,
        'Title' : 'Data Structures and Algorithms with Visualizations – Full Course (Java)',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/2ZLl8GAk1X4?si=g4T18MgR8Ik4tTOZ',
        'context' : 'The course walks you through multiple Java algorithms, data structure problems, and their solutions with step-by-step visualizations, so that you are actually learning instead of blindly memorizing solutions.',
        'imageUrl': require('../assets/cources-tmb/dsa.jpg'),
        'MainCat': 'Data Structures and Algorithms',
        'Stack': 'Java',
        'additional': 'By Visual and Graphics',
        'Language' : 'English'
    },
    {
        'sno'   : 8,
        'Title' : 'Python for Data Science - Course for Beginners (Learn Python, Pandas, NumPy, Matplotlib)',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/LHBE6Q9XlzI?si=ZGlDaiIW1jCohaTw',
        'context' : 'This Python data science course will take you from knowing nothing about Python to coding and analyzing data with Python using tools like Pandas, NumPy, and Matplotlib.',
        'imageUrl': require('../assets/cources-tmb/pythonds.jpg'),
        'MainCat': 'Data Science',
        'Stack': 'Python',
        'additional': 'Python, Pandas, NumPy, Matplotlib',
        'Language' : 'English'
    },
    {
        'sno'   : 9,
        'Title' : 'JavaScript Game Development Course for Beginners',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/GFO_txvwK_c?si=YIxhpF5DQh9dQl1v',
        'context' : 'Learn to make 2D games with HTML, CSS & plain vanilla JavaScript, no frameworks and no libraries! From sprite animation to state management, in this series of projects you will learn everything you need to make your own 2D animated games! We will go step by step explaining each technique on a small standalone codebase and then we will use everything we learned to make a single final game.',
        'imageUrl': require('../assets/cources-tmb/jsgame.jpg'),
        'MainCat': 'Game Development',
        'Stack': 'JavaScript',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 10,
        'Title' : 'C++ Programming Course - Beginner to Advanced',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/8jLOx1hD3_o?si=KVHo4JifH7yDfFuj',
        'context' : 'Learn modern C++ 20 programming in this comprehensive course.',
        'imageUrl': require('../assets/cources-tmb/cpp31.jpg'),
        'MainCat': 'Programming',
        'Stack': 'C++',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 11,
        'Title' : 'Flask Course - Python Web Application Development',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/Qr4QMBUPxWo?si=TsOibkkcvkakZgQP',
        'context' : 'Learn the Flask Python web framework by building your own e-commerce website with its own authentication system.',
        'imageUrl': require('../assets/cources-tmb/flask.jpg'),
        'MainCat': 'Web Development',
        'Stack': 'Python',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 12,
        'Title' : 'MongoDB Complete Course Tutorial in Hindi🔥Free Notes + Projects',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/rU9ZODw5yvU?si=uZp8O1AIlUsLxZrE',
        'context' : 'Complete MongoDB Course Tutorial in Hindi. Where we will learn Basic to Advanced MongoDB including Aggregation Framework and Projects with MongoDB Drivers.  Whether you are new to databases or a seasoned coder, this one-stop tutorial has you covered.',
        'imageUrl': require('../assets/cources-tmb/mongoHindi.jpg'),
        'MainCat': 'Web Development',
        'Stack': 'Mongodb',
        'additional': '',
        'Language' : 'Hindi'
    },
    {
        'sno'   : 13,
        'Title' : 'React.js Complete Tutorial for Beginners in Hindi | 5 Projects + Free Notes',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/EHTWMpD6S_0?si=Rt74XFydIHrgFyPN',
        'context' : 'Complete React JS Full Course tutorial for Beginners in Hindi! In this single video, we will cover everything you need to know about React JS in 2024.',
        'imageUrl': require('../assets/cources-tmb/reactTahppa.jpg'),
        'MainCat': 'Web Development',
        'Stack': 'React js',
        'additional': '',
        'Language' : 'Hindi'
    },
    {
        'sno'   : 14,
        'Title' : 'Express JS Tutorial in Hindi ',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/7H_QH9nipNs?si=cqYG8bKtUc7A5Lyd',
        'context' : ' In this Express Js course, we will talk about building sites using express. We will build a blog website using the express framework.',
        'imageUrl': require('../assets/cources-tmb/express.jpg'),
        'MainCat': 'Web Development',
        'Stack': 'Express',
        'additional': '',
        'Language' : 'Hindi'
    },
    {
        'sno'   : 15,
        'Title' : 'Node js complete tutorial in Hindi - Full Node course in one video',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/VrQgmNY96wo?si=87gXlCt-8Nj2szcO',
        'context' : 'complete course in one video by anil side. this is a node js complete series in one video in Hindi Langauge.',
        'imageUrl': require('../assets/cources-tmb/nodeH.jpg'),
        'MainCat': 'Web Development',
        'Stack': 'Node js',
        'additional': '',
        'Language' : 'Hindi'
    },
    {
        'sno'   : 16,
        'Title' : 'Learn Unity Beginner/Intermediate 2023 (FREE COMPLETE Course - Unity Tutorial)',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/AmGSEH7QcDg?si=0JJTEz68Qc6cHLdf',
        'context' : ' Learn How to Make Games with Unity and C# in this massive FREE course. I have  been working for the past 3 months on this very exciting project, a 10 hour course making a complete game from scratch! The game features lots of interesting systems which makes for a great learning project.This is for both Beginners and Intermediate users who want to learn how to write good high quality clean code and learn to manage a relatively complex project with a good structure.The game itself is a fun Arcade game, using what you learn by making this game will enable you to build just about any game you can think of.',
        'imageUrl': require('../assets/cources-tmb/unity.jpg'),
        'MainCat': 'Game Development',
        'Stack': 'Unity',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 17,
        'Title' : 'Unity Game Development Tutorials in Hindi',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtube.com/playlist?list=PLCqWuVe6WFLJW4urlRk1501OkAGVQtX8q&si=sv072UocxUsbW5g6',
        'context' : 'This course is perfect course for learn unity and basic c# in hindi',
        'imageUrl': require('../assets/cources-tmb/unityHindi.jpg'),
        'MainCat': 'Game Development',
        'Stack': 'Unity',
        'additional': '',
        'Language' : 'Hindi'
    },
    {
        'sno'   : 18,
        'Title' : 'Unity C# Scripting Tutorial For Beginners-Learn C# For Unity',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtube.com/playlist?list=PLytjVIyAOStpT8xJyijH4uG4nEPexvj18&si=VIrfwaSQJfY9v-Xs',
        'context' : 'Unity C# Scripting Tutorial For Beginners. Learn C# for game development with unity. Learn Unity game development step by step with c#. Create games with C# and unity with this unity c# scripting tutorial for unity game development',
        'imageUrl': require('../assets/cources-tmb/unity C.jpg'),
        'MainCat': 'Game Development',
        'Stack': 'Unity',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 19,
        'Title' : 'Learn Unity - Beginners Game Development Tutorial',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/gB1F9G0JXOo?si=GvNa2AeTvOvGrItf',
        'context' : 'Learn to develop games using the Unity game engine in this complete course for beginners. This course will get you up and running with Unity. Free game assets included!',
        'imageUrl': require('../assets/cources-tmb/learnUnity.jpg'),
        'MainCat': 'Game Development',
        'Stack': 'Unity',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 20,
        'Title' : 'Python Game Development Using Pygame In Hindi',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtube.com/playlist?list=PLu0W_9lII9ailUQcxEPZrWgDoL36BtPYb&si=CSuTVW1L1Ms2toHK',
        'context' : 'Learn game development with pygame and python in hindi',
        'imageUrl': require('../assets/cources-tmb/py.jpg'),
        'MainCat': 'Game Development',
        'Stack': 'PyGame',
        'additional': '',
        'Language' : 'Hindi'
    },
    {
        'sno'   : 21,
        'Title' : 'Unreal Engine Basics in Hindi || Must watch Beginner Tutorial',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/kSJPEevIfOU?si=yTKj6DKc0irUIxpy',
        'context' : 'Lets go and learn the important basics of unreal engine and that too in Hindi. You may use Unreal Engine 5 or even Unreal Engine 4 depending upon what you are targeting.',
        'imageUrl': require('../assets/cources-tmb/ueHindi.jpg'),
        'MainCat': 'Game Development',
        'Stack': 'Unreal Engine',
        'additional': '',
        'Language' : 'Hindi'
    },
    {
        'sno'   : 22,
        'Title' : 'Pygame Tutorial for Beginners - Python Game Development Course',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/FfWpgLFMI7w?si=_R0EZVHGcZCSzfhM',
        'context' : 'Learn how to use Pygame to code games with Python. In this full tutorial course, you will learn Pygame by building a space invaders game. The course will help you understand the main game development concepts like moving characters, shooting bullets, and more',
        'imageUrl': require('../assets/cources-tmb/pygmEng.jpg'),
        'MainCat': 'Game Development',
        'Stack': 'Python',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 23,
        'Title' : 'C++ For Unreal Engine | Learn C++ For Unreal Engine | C++ Tutorial For Unreal Engine',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/6UlU_FsicK8?si=K_F0LPLBSiDzaVeS',
        'context' : 'This Course is intended for intermediate programmers who want to learn how to program Unreal Engine games using C++. Learners should complete at least one other programming Specialization on one programming course in high school or college before starting this Specialization. The first course assumes that level of programming experience, and throughout the 4 courses in the Specialization you will learn how to program in C++ and how to use that C++ knowledge to program Unreal Engine games. The C++ and Unreal material in the courses in the Specialization is slightly less comprehensive than the content in the first two game programming courses at UCCS.',
        'imageUrl': require('../assets/cources-tmb/uec.jpg'),
        'MainCat': 'Game Development',
        'Stack': 'Unreal Engine',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 24,
        'Title' : 'Unreal Engine 5: Full Course for Beginners',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/6UlU_FsicK8?si=eCiValMWsXhZln6G',
        'context' : 'Learn how to create games with Unreal Engine 5 in this full course for beginners. This course will give you a solid foundation and will enable you to be able to develop any sort of game in Unreal Engine 5',
        'imageUrl': require('../assets/cources-tmb/ue5.jpg'),
        'MainCat': 'Game Development',
        'Stack': 'Unreal Engine',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 25,
        'Title' : 'React Native Course – Android and iOS App Development',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/obH0Po_RdWk?si=vxaILCYEIJZxzDfY',
        'context' : 'Master React Native with this comprehensive course, covering everything from the basics of setup and components to advanced topics like navigation and fetching API data. Learn to build a weather app from scratch, complete with a sleek user interface and real-time data integration, while exploring concepts like state management, hooks, and styling.',
        'imageUrl': require('../assets/cources-tmb/reactnative.jpg'),
        'MainCat': 'App Development',
        'Stack': 'React Native',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 26,
        'Title' : 'Flutter Course for Beginners – 37-hour Cross Platform App Development Tutorial',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/VPvVD8t02U8?si=a06_acM7VJJyNnYM',
        'context' : 'Learn how to use Flutter in this complete course for beginners. Flutter is an open-source UI software development kit used to create cross-platform applications for iOS, Android, Windows, Mac, and more.',
        'imageUrl': require('../assets/cources-tmb/flutter.jpg'),
        'MainCat': 'App Development',
        'Stack': 'Flutter',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 27,
        'Title' : 'React Native full Course with Redux in Hindi | Complete React-native in One Video!',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/KBWWxJdsFlY?si=MqDcdJ8A_iuuKTow',
        'context' : 'This is one of the best course of react native in hindi avilable on youtube.',
        'imageUrl': require('../assets/cources-tmb/reactnative.jpg'),
        'MainCat': 'App Development',
        'Stack': 'React Native',
        'additional': '',
        'Language' : 'Hindi'
    },
    {
        'sno'   : 28,
        'Title' : 'Kotlin & Android Development Course: Build a Quiz Application',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/kNghEbknLs8?si=WWC_r6IR1qiYt1V0',
        'context' : 'In this Kotlin and Android course, you will learn about collections, generics, lambdas, Android Studio, widgets, and more. You will also learn how to build a full quiz application for Android devices.',
        'imageUrl': require('../assets/cources-tmb/AppKt.jpg'),
        'MainCat': 'App Development',
        'Stack': 'Kotlin',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 29,
        'Title' : 'Android Development Tutorial For Beginners In Hindi (With Notes)',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/mXjZQX3UzOs?si=FqGK_gC3KRifD2Sx',
        'context' : 'Learn Android in One Video: In this Android App Development tutorial, we will learn how to make beautiful android applications from scratch in Hindi. This Android tutorial in Hindi will teach you how to make Android apps that sell from scratch. We will learn to make apps and publish them to the play store in 2021. We will learn how to make money from our android application through various means. I will also share some of my personal secrets techniques for making money online using Android Applications. You can become a successful android developer after watching this video.',
        'imageUrl': require('../assets/cources-tmb/androidCWH.jpg'),
        'MainCat': 'App Development',
        'Stack': 'Java',
        'additional': 'Publish apps on playstore',
        'Language' : 'Hindi'
    },
    {
        'sno'   : 30,
        'Title' : 'Android Development for Beginners - Full Course',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/fis26HvvDII?si=ed3ZPgAP_EPmNJlq',
        'context' : 'Learn how to develop an android app from scratch in this full course for beginners. No prior programming experience required! I will also share some of my personal secrets techniques for making money online using Android Applications. You can become a successful android developer after watching this video.',
        'imageUrl': require('../assets/cources-tmb/andoid.jpg'),
        'MainCat': 'App Development',
        'Stack': 'Java',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 31,
        'Title' : 'Create a C# Application from Start to Finish - Complete Course',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/wfWxdh-_k_4?si=7lIoSPdHJDQLUjKh',
        'context' : 'In this comprehensive 24-hour-long course, you will learn to use C# to build a complete application from start to finish.  Using .net and Visual Studio, we will construct a tournament tracker application that is fit to launch. The application uses Winforms, a class library, events, SQL database, text file data storage (in CSV format), custom events and more. ',
        'imageUrl': require('../assets/cources-tmb/csdev.jpg'),
        'MainCat': 'Softwear Development',
        'Stack': 'C#',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 32,
        'Title' : 'Java Programming for Beginners – Full Course',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/A74TOX803D0?si=9npJmsDFpuTj90My',
        'context' : 'Learn the Java programming language in this complete beginners course. You will learn all the main features of Java (version 17) and how to use Java for your own projects. ',
        'imageUrl': require('../assets/cources-tmb/javaEng.jpg'),
        'MainCat': 'programming',
        'Stack': 'Java',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 33,
        'Title' : 'Java Tutorials For Beginners In Hindi',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : '',
        'context' : 'In this complete Core + Advance Java tutorial for beginners in hindi, we will see complete java topics covered in hindi. This java complete tutorial will cover topics like Downloading Java, Installation of Java, java JVM, java inheritance, java inheritance & polymorphism and other complete java tutorial topics will be covered. This Java Tutorial for Beginners in Hindi can be used to learn Java in Hindi. Hope you like this Java Tutorial in Hindi. I am very excited to launch this Java full course for you',
        'imageUrl': require('../assets/cources-tmb/javaCwh.jpg'),
        'MainCat': 'programming',
        'Stack': 'Java',
        'additional': '',
        'Language' : 'Hindi'
    },
    {
        'sno'   : 34,
        'Title' : 'JavaScript Tutorials for Beginners in Hindi',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtube.com/playlist?list=PLu0W_9lII9ahR1blWXxgSlL4y9iQBnLpR&si=9PAnvAB-fg3iNCod',
        'context' : 'JavaScript Course in Hindi: This Javascript tutorial in Hindi course is designed for beginners with an aim to take JavaScript/ES6 and its concepts to an advanced level. Master JavaScript with this course now and you will be able to create a website easily after watching this. This tutorial series is for all those people who want to build a career in the Web development industry. This video series starts with Javascript basics and then moves toward advanced Javascript. ',
        'imageUrl': require('../assets/cources-tmb/jsHi.jpg'),
        'MainCat': 'programming',
        'Stack': 'JavaScript',
        'additional': '',
        'Language' : 'Hindi'
    },
    {
        'sno'   : 35,
        'Title' : 'JavaScript Programming - Full Course',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/jS4aFq5-91M?si=fst5U9hT4vNqlybI',
        'context' : 'Learn JavaScript from scratch by solving over a hundred different coding challenges. ',
        'imageUrl': require('../assets/cources-tmb/jsEng.jpg'),
        'MainCat': 'programming',
        'Stack': 'JavaScript',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 36,
        'Title' : 'C Programming Tutorial for Beginners',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/KJgsSFOSQv0?si=Ouas8ZGOwK5EwaS9',
        'context' : 'This course will give you a full introduction into all of the core concepts in the C programming language.',
        'imageUrl': require('../assets/cources-tmb/c.jpg'),
        'MainCat': 'programming',
        'Stack': 'C',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 37,
        'Title' : 'C# Tutorial In Hindi',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/SuLiu5AK9Ps?si=JmFap8F9gCxZ4qWa',
        'context' : 'In this C sharp tutorial for beginners in Hindi, I have touched upon the .NET framework and how to use C# and .Net to program beautiful applications.',
        'imageUrl': require('../assets/cources-tmb/csharphindi.jpg'),
        'MainCat': 'programming',
        'Stack': 'C#',
        'additional': '',
        'Language' : 'Hindi'
    },
    {
        'sno'   : 38,
        'Title' : 'C Language Tutorial for Beginners (with Notes & Practice Questions)',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/irqbmMNs2Bo?si=Kk_C-9WnPZqQKKdt',
        'context' : 'You can join the  NEW Web Development batch using the below link',
        'imageUrl': require('../assets/cources-tmb/cHindi.jpg'),
        'MainCat': 'programming',
        'Stack': 'C',
        'additional': '',
        'Language' : 'Hindi'
    },
    {
        'sno'   : 39,
        'Title' : 'C++ Tutorials In Hindi',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtube.com/playlist?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&si=UxHvQCI24pfUcFfe',
        'context' : 'This C++ tutorials for beginners will teach you all the c plus plus concepts from the very starting to the end. This Cpp course will introduce you to programming and will continue the discussion on how to write efficient, fast and better CPP programs.',
        'imageUrl': require('../assets/cources-tmb/cppHi.jpg'),
        'MainCat': 'programming',
        'Stack': 'C++',
        'additional': '',
        'Language' : 'Hindi'
    },
    {
        'sno'   : 40,
        'Title' : 'Python for Beginners (Full Course)',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtube.com/playlist?list=PLu0W_9lII9agwh1XjRt242xIpHhPT2llg&si=0bp9m0Oy0KI3ZJee',
        'context' : 'Python is one of the most demanded programming languages in the job market. Surprisingly, it is equally easy to learn and master Python. This python tutorial for absolute beginners in Hindi series will  focus on teaching you python concepts from the ground up, to an advanced level. With this 100-day challenge now and you will be able to get a job easily.',
        'imageUrl': require('../assets/cources-tmb/pycwh.jpg'),
        'MainCat': 'programming',
        'Stack': 'Python',
        'additional': '',
        'Language' : 'Hindi'
    },
    {
        'sno'   : 41,
        'Title' : 'Learn Python - Full Course for Beginners [Tutorial]',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/rfscVS0vtbw?si=1pL07QiIyQWdiFS9',
        'context' : 'This course will give you a full introduction into all of the core concepts in python. Follow along with the videos and you will be a python programmer in no time!',
        'imageUrl': require('../assets/cources-tmb/pythonEng.jpg'),
        'MainCat': 'programming',
        'Stack': 'Python',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 42,
        'Title' : 'Learn Kotlin Programming : Full Course for Beginners',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/EExSSotojVI?si=3m9uCX8Ja07pkBXv',
        'context' : 'In this full Kotlin course, you will learn the most popular programming language on Android and start building your own apps.',
        'imageUrl': require('../assets/cources-tmb/kotlinpro.jpg'),
        'MainCat': 'programming',
        'Stack': 'Kotlin',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 43,
        'Title' : 'Ruby Programming Language - Full Course',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/t_ispmWmdjY?si=4aIaFoz9nxAG54mv',
        'context' : 'Learn the Ruby programming language in this full course / tutorial. The course is designed for new programmers, and will introduce common programming topics using the ruby language',
        'imageUrl': require('../assets/cources-tmb/ruby.jpg'),
        'MainCat': 'programming',
        'Stack': 'Ruby',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 44,
        'Title' : 'Swift Programming Tutorial : Full Course for Beginners',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/8Xg7E9shq0U?si=3xJeZ3AM8L5Au6Sq',
        'context' : 'In this video, we will go through every modern aspect of Swift as a programming language including, variables, constants, functions, structures, classes, protocols. extensions, asynchronous programming, generics and much more. This video will lay the foundation for learning Swift for those who are not familiar with Swift already.',
        'imageUrl': require('../assets/cources-tmb/swift.jpg'),
        'MainCat': 'programming',
        'Stack': 'Swift',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 45,
        'Title' : 'iOS Development Course - Use Swift 5 and UIKit to Build a Netflix Clone',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/KCgYDCKqato?si=i2WZR2gBkz5QcYHx',
        'context' : 'Learn how to use Swift 5, UIKit, and Xcode to develop iOS apps by building a Netflix clone. You will learn how to implement the MVVM design pattern.',
        'imageUrl': require('../assets/cources-tmb/ios.jpg'),
        'MainCat': 'App Development',
        'Stack': 'Ios',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 46,
        'Title' : 'R Programming Full Course for 2023 | R Programming For Beginners | R Tutorial',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://www.youtube.com/live/Q5g6lYUn6Q4?si=g_IoyVf8FboLk5Eu',
        'context' : 'This R Programming Full Course for 2023by Simplilearn will help you master the concepts of R programming in 7 Hours. In this R Programming for Beginners tutorial,  we will learn about What is R, variables, and data types in R. This R Programming for Beginners is the ideal video for anyone starting with R Programming and Data Analysis. We will Understand Data Handling, Manipulation, and Visualization in R. So, lets get started with this R Tutorial!',
        'imageUrl': require('../assets/cources-tmb/r.jpg'),
        'MainCat': 'programming',
        'Stack': 'R',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 47,
        'Title' : 'Learn ASP.NET Core 3.1 - Full Course for Beginners [Tutorial]',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/C5cnZ-gZy2I?si=7QcfHYmEjVJdr63H',
        'context' : 'After learning about the history and basics of ASP.NET Core, you will learn how to build a small book list application with CRUD operations. You will learn how to use the Entity Framework for integration with a database with ASP.NET Core Razor Pages.',
        'imageUrl': require('../assets/cources-tmb/net.jpg'),
        'MainCat': 'Web Development',
        'Stack': '.Net',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 48,
        'Title' : 'SQL Tutorial - Full Database Course for Beginners',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/HXV3zeQKqGY?si=yCuwkioHogzkuSP4',
        'context' : 'The course is designed for beginners to SQL and database management systems, and will introduce common database management topics.',
        'imageUrl': require('../assets/cources-tmb/sql.jpg'),
        'MainCat': 'programming',
        'Stack': 'SQL',
        'additional': '',
        'Language' : 'English'
    },
    {
        'sno'   : 49,
        'Title' : 'APIs for Beginners 2023 - How to use an API (Full Course / Tutorial)',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/WXsD0ZgxjRw?si=lCtV3QHDPmjoK9GG',
        'context' : 'What is an API? Learn all about APIs (Application Programming Interfaces) in this full tutorial for beginners. You will learn what APIs do, why APIs exist, and the many benefits of APIs. APIs are used all the time in programming and web development so it is important to understand how to use them.',
        'imageUrl': require('../assets/cources-tmb/api.jpg'),
        'MainCat': 'API',
        'Stack': 'API',
        'additional': 'Using Spotify Web Api',
        'Language' : 'English'
    },
    {
        'sno'   : 50,
        'Title' : 'Harvard CS50 – Full Computer Science University Course',
        'isPaid'  :  false,
        'platform': 'Youtube',
        'Link' : 'https://youtu.be/8mAITcNt710?si=HMq-P8Ttcm-Bf9gI',
        'context' : 'Learn the basics of computer science from Harvard University. This is CS50, an introduction to the intellectual enterprises of computer science and the art of programming.',
        'imageUrl': require('../assets/cources-tmb/cs50.jpg'),
        'MainCat': 'CS 50',
        'Stack': 'CS 50',
        'additional': '',
        'Language' : 'English'
    },
   ]

  